In [33]:
import pandas as pd
from loader import load_data, URL

In [34]:
df = load_data(URL)
df.head()

   uid  ru_wiki_pageid                                               text
0    0           58311  ЦСКА — советский и российский профессиональный...
1    1           58311  В первом сезоне в составе Континентальной хокк...
2    2           58311  В межсезонье 1992 года «армейскую» команду пок...
3    3           58311  Однако ни Тихонов, ни Гущин, не согласились с ...
4    4           58311  ЦСКА Александра Волчкова сезон 1996/97 провел ...

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56952 entries, 0 to 56951
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   uid             56952 non-null  int64
 1   ru_wiki_pageid  56952 non-null  int64
 2   text            56952 non-null  str
dtypes: int64(2), str(1)
memory usage: 1.3 MB

In [36]:
df.ru_wiki_pageid.nunique()

9105

In [37]:
df.uid.nunique()

56952

In [38]:
df.duplicated(subset=['text']).sum()

np.int64(126)

In [39]:
df[df.duplicated(subset=['text'], keep=False)]

,uid,ru_wiki_pageid,text
586,586,2697155,Русский ампир (примерно 1812-1830 годы) явился...
1484,1484,1077294,2008 — «Лучшие песни». Песни Юлии и Виктора На...
1504,1504,8050376,2008 — «Лучшие песни». Песни Юлии и Виктора На...
1887,1887,7502425,В 1-ю корзину попадают: действующие победители...
1962,1962,15996,Древнейшие древнеегипетские математические тек...
...,...,...,...
56312,56312,2755908,Системы органов животных
56324,56324,663082,Системы органов человека
56327,56327,663082,Системы органов животных
56384,56384,4113123,.
56741,56741,229622,.

In [40]:
df.text.str.len().describe()

count    56952.000000
mean       448.516610
std        415.260131
min          1.000000
25%        172.000000
50%        343.000000
75%        600.000000
max      11010.000000
Name: text, dtype: float64

In [44]:
df[df.text.str.len() > 1000]

,uid,ru_wiki_pageid,text
2,2,58311,В межсезонье 1992 года «армейскую» команду пок...
5,5,40178,В сентябре 1992 года ЦСКА стартовал в Лиге чем...
6,6,40178,В ноябре 2003 года вместо Валерия Газзаева у р...
7,7,40178,После окончания сезона 2017/18 завершили карье...
8,8,40178,История футбольного клуба ЦСКА началась в 1911...
...,...,...,...
56920,56920,104593,В 1968 и 1969 году сборная Северной Ирландии в...
56922,56922,104593,Финал состоялся 29 мая 1968 года на стадионе «...
56940,56940,70387,Площадка в русском крокете имеет размер 11 м н...
56943,56943,1134329,Энергетический эффект химической реакции всегд...
56944,56944,39408,К концу XVIII века Россия занимала первое мест...

In [41]:
df.text.unique()

<StringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'ЦСКА — советский и российский профессиональный хоккейный клуб из Москвы, выступающий в Континентальной хоккейной лиге. Основан в 1946 году под названием ЦДКА (Центральный дом Красной Армии). В 1951 году переименован в ЦДСА (Центральный дом Советской Армии), а в 1954 в ЦСК МО (Центральный спортивный клуб Министерства обороны), под которым выступал до 1959 года, и с тех пор носит название ЦСКА (Центральный Спортивный Клуб Армии).',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               'В первом сезоне в составе Континентальной хоккейной лиги ЦСКА выиграл дивизион Тарасова, но в плей-офф с трудом обыграл «Ладу» (3-2 по сумме встреч) и всухую проиграл «Динамо» (0-3). В конце сезона тренерский тандем Быков-Захаркин покинул команду, аргументировав своё решение желанием сосредоточиться на работе в сборной России, однако уже через несколько недель подписали контракт с командой «Салават Юлаев», таким образом продолжив совмещать работу в сборной и в клубе.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'В межсезонье 1992 года «армейскую» команду покинули все лидеры, а Министерство обороны уже Российской Федерации, находясь в тяжелейшем финансовом и организационном положении, не могло оказать своей штатной команде ровным счетом никакой помощи. «Армейский» хоккей рухнул. Сезон 1992/93 стал самым черным в истории ЦСКА. Команда заняла предпоследнее место в первом чемпионате Межнациональной хоккейной лиги, и, казалось, что для хоккейного клуба скоро все кончится печально. Однако в июле 1993 года состоялось неожиданное событие. Хоккейный клуб ЦСКА подписал договор о сотрудничестве с Хоккейным клубом НХЛ «Питтсбург Пингвинз». Хозяева «Пингвинов», входившие со своим бизнесом на зарождающийся российский рынок, приняли решение продвигаться в Россию через хоккей. И лучшего кандидата, чем ЦСКА, придумать не могли. Благодаря деньгам «Пингвинов», ЦСКА постепенно начал оживать. Безусловно, сотрудничество носило обоюдовыгодный характер. Хозяева «Питтсбурга» получали некоторые привилегии в отношении перехода воспитанников хоккейного клуба в свою организацию. В одной из североамериканских лиг была учреждена команда «Russian Pinguins», где выступали игроки ЦСКА.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Однако ни Тихонов, ни Гущин, не согласились с решениями Министра обороны, и своей отставки не признали. Сохраняя права на бренд «ЦСКА», и на частную фирму ООО «ХК ЦСКА», учрежденную в 1993 году для проведения коммерческой деятельности, уже бывшие руководители клуба заявили «ХК ЦСКА» в качестве участника образовавшейся Российской Хоккейной Лиги. Совет РХЛ, по итогам прений, принял решение о включении в соревнования среди команд Суперлиги именно тихоновский «ХК ЦСКА».',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'ЦСКА Александра Волчкова сезон 1996/97 провел в Высшей лиге, и по итогам турнира завоевал путевку в Суперлигу. В сезоне 1996/97 в Суперлиге РХЛ выступали два ЦСКА. Между командами состоялось два дерби, победу в которых оба раза одержал ЦСКА Волчкова. По итогам сезона 1997/98 ЦСКА сохранил прописку в Суперлиге, ХК ЦСКА же вылетел в Высшую лигу, где провел следующие 4 сезона. Тогда же, в 1998 году, Виктор Тихонов предпринял первые шаги к объединению двух клубов, однако его инициатива не увенчалась успехом. ',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'В сентябре 1992 года ЦСКА стартовал в Лиге чемпионов. В первом матче армейцы играли против исландского клуба «Викингур», первый матч закончился со счётом 1:0, а второй 4:2 в пользу москвичей. А в следующем матче армейцы встречались с действующим на то время обладателем Кубка чемпионов — «Барселоной». Первый матч прошёл 21 октября 1992 года в присутствии 40000 зрителей и завершился со счётом 1:1. У армейцев отличился Александр Гришин, а у испанцев — Бегиристайн. Второй матч прошёл 4 ноября 1992 года, на знаменитом домашнем стадионе «Барселоны» — «Камп Ноу», в присутствии 80000 болельщиков. Хозяева открыли счёт в матче уже на 12 минуте игры, отличился Надаль, а на 31 минуте Бегиристайн удвоил счёт в матче. За несколько минут до конца первого тайма Евгений Бушманов сумел обыграть вратаря «Барсы» Субисаррету и сократил разрыв в счёте. После перерыва, на 57 минуте, Денис Машкарин сравнял счёт. А ещё через 4 минуты Дмитрий Карсаков, после паса Ильшата Файзулина установил окончательный счёт в матче 2:3. После этой победы ЦСКА вышел в групповой этап. Несмотря на победу над «Барселоной», в своей группе ЦСКА занял последнее место и завершил выступление в еврокубках.',
 'В ноябре 2003 года вместо Валерия Газзаева у руля команды встал португальский специалист Артур Жорже, под руководством нового тренера команда одержала победу 3:1 в матче на Суперкубок России против московского «Спартака». В сезоне 2004 года главным спонсором ЦСКА стала компания «Сибнефть». За счёт финансовых отчислений спонсора были приобретены несколько футболистов. Из московского «Локомотива» перешёл защитник Сергей Игнашевич, из волгоградского «Ротора» в команду пришёл Евгений Алдонин, из аргентинского клуба «Ривер Плейт» — Осмар Феррейра, также были приобретены Даниэл Карвальо, Владимир Габулов, Юрий Жирков и Чиди Одиа. При этом команду покинула большая группа игроков, игравших важную роль в чемпионском сезоне: Игорь Яновский, Андрей Соломатин, Спартак Гогниев, Денис Попов, Денис Евсиков, а также редко выходившие на поле: Александр Беркетов, Александр Гейнрих, Вартан Мазалов и Артур Тлисов. Однако, несмотря на все приобретения, дела в чемпионате шли плохо, к концу первого круга команда занимала пятое место с 20 очками. В связи с этим, Жорже был уволен, а его место вновь занял Валерий Газзаев. Летом были приобретены бразильский нападающий Вагнер Лав, его коллега по амплуа Сергей Даду из Молдавии и сербский полузащитник Милош Красич. Газзаеву удалось поправить турнирное положение команды, и за два тура до финиша ЦСКА занимал первое место. Однако в следующем туре армейцы оступились, сыграв вничью с «Динамо», и пропустили вперёд «Локомотив». В результате ЦСКА занял второе место, отстав от чемпиона — московского «Локомотива» — всего лишь на одно очко. В своей группе Лиги чемпионов ЦСКА удалось занять третье место, это позволило принять участие в кубке УЕФА весной 2005 года.',
                                                                                                                                                                                                                                         'После окончания сезона 2017/18 завершили карьеры Алексей и Василий Березуцкие, Сергей Игнашевич вошел в тренерский штаб команды, закончились контракты у Понтуса Вернблума, Бибраса Натхо и Георги Миланова, был продан в «Монако» за € 30 млн Александр Головин, вернулся в Бразилию Витиньо. Команда начала «строиться» заново — впервые за несколько сезонов была проведена масштабная кампания по приглашению преимущественно молодых футболистов, на которых суммарно потратили не более € 10 млн. Команду пополнили исландцы Хёрдур Магнуссон и Арнор Сигурдссон, у «Эвертона» арендован Никола Влашич, бесплатно пришёл Абель Эрнандес, появились молодые российские игроки Ильзат Ахметов и Иван Обляков, вернулись из аренды и стали играть в команде Никита Чернов и Дмитрий Ефремов. В Лиге Чемпионов 2018/19 ЦСКА попал в одну группу с «Реалом», «Ромой» и «Викторией Пльзень». Самое начало сезона 2018/19 вышло нестабильным — обилие травм и несыгранность молодых игроков дали о себе знать. Однако с начала августа по начало октября 2018 года ЦСКА выдал серию из 9 игр подряд без поражений (5 побед, 4 ничьих) в чемпионате и Лиге Чемпионов — в этом промежутке был обыгран «Реал» (1:0) и сыграна ничья со «Спартаком» (1:1). Однако в октябре команда проиграла 4 матча из 5, в том числе дома прямым конкурентам за медали — «Локомотиву» и «Краснодару». На зимнее межсезонье ЦСКА ушёл третьм в таблице РПЛ, но вылетел из Лиги Чемпионов, не смотря на то, что дважды обыграл «Реал» (1:0; 3:0).',
                                                                                                                                                                                                                                                                                                                                                                                                                           'История футбольного клуба ЦСКА началась в 1911 году, когда в Обществе любителей лыжного спорта (ОЛЛС) была организована футбольная секция. На базе этой футбольной секции было сформировано три команды, которые в том же году впервые приняли участие в чемпионате Москвы в классе «Б». 14 (27) августа 1911 год был сыгран первый официальный матч команды ОЛЛС с клубом «Вега». Матч закончился победой футболистов ОЛЛС со счётом 6:2. В 1917 году команда завоевала первое место в Казанской лиге (первенстве команд, располагавшихся в дачных местностях вдоль Казанской железной дороги) и вышла в класс «А» чемпионата Москвы, где выступала до 1922 года.После сезона 1917 года часть второй команды ОЛЛС перешла в первую. В 1921 году в осеннем первенстве Москвы (Кубке Фульда) чемпион определялся в «золотом матче», в котором принимали участие команды ОЛЛС и КФС. Команда КФС выиграла со счётом 6:0. В сезоне 1922 года футболисты ОЛЛС выиграли весенний чемпионат Москвы и заняли второе место в осеннем. В том же году ОЛЛС выиграло «Кубок КФС — «Коломяги»», в финале которого по регламенту встречались победители первой и второй лиг московского чемпионата, и «Кубок Тосмена», в котором встречались чемпионы Москвы и Петрограда.Сезон 1922 года был последним, в котором команда выступала под названием ОЛЛС.',
                 'В 1960 году во главе ЦСК МО вновь стал Григорий Пинаичев. В этом же году главный армейский клуб страны в последний раз сменил своё название и стал называться ЦСКА. В сезоне 1960 года формула чемпионата была изменена, количество команд высшей лиги было увеличено до 22 коллективов, распределённых в две подгруппы по 11 команд в каждой. В финальный этап чемпионата, в котором разыгрывались медали, выходило по три команды из каждой подгруппы. ЦСКА выступал во второй подгруппе, в которой за выход в финальный этап боролись «Динамо» (Киев), «Спартак» (Москва) и «Локомотив» (Москва). 19 июля 1960 года на стадионе Лужники проходила встреча ЦСКА — «Динамо» Киев, которая во многом решала судьбу выхода в финальный этап. На 65 минуте встречи, при счёте 1:1, за фол в пределах штрафной площадки рижский судья Эдгар Клавс назначил в ворота армейцев пенальти. Пробил пенальти нападающий киевлян Валерий Лобановский, однако вратарь москвичей Юрий Коротких сумел отбить мяч в прыжке. Судья принял решение перебить пенальти, Лобановский со второй попытки забил. Через некоторое время, крайний полузащитник москвичей Евгений Крылов сделал подкат под футболиста Динамо Олега Базилевича, за что получил красную карточку. После удаления Крылова на поле выбежали 150—200 раздосадованных болельщиков ЦСКА, некоторые из которых напали на арбитра. Игра была остановлена, армейцам засчитали поражение. После матча несколько десятков болельщиков были задержаны и получили по 15 суток, ещё четверо болельщиков были осуждены на сроки от двух до шести лет. ЦСКА все же пробился в финальный турнир, однако занял там всего лишь последнее, шестое, место. По окончании сезона весь тренерский штаб ЦСКА был уволен.',
 ...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'ΔHoреакции = ΣΔHof (продукты) — ΣΔHof (реагенты).Термохимические эффекты можно включать в химические реакции. Химические уравнения в которых указано количество выделившейся или поглощенной теплоты, называются термохимическими уравнениями. Реакции, сопровождающиеся выделением тепла в окружающую среду имеют отрицательный тепловой эффект и называются экзотермическими. Реакции, сопровождающиеся поглощением тепла имеют положительный тепловой эффект и называются эндотермическими. Тепловой эффект обычно относится к одному молю прореагировавшего исходного вещества, стехиометрический коэффициент которого максимален.',

In [43]:
mask = df['text'].str.contains('�')
df[mask].head()

Empty DataFrame
Columns: [uid, ru_wiki_pageid, text]
Index: []